spring:
  application:
    name: hello-spring-cloud-config
  cloud:
    config:
      label: master
      server:
        git:
          uri: https://github.com/LKLearn/cloudConfig
          search-paths: respo
          username: LKLearn
          password: zhangsm525700H
#这是cloud config 的 测试文件
server:
  port: 8888
  
foo: abc

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/